### ISSUE TITLE
How can I get p values for all the positions?

### ISSUE THREAD

**Issue by bhargava-morampalli** [bartongroup/yanocomp#9]
The default result is for most significant position in the RNA but is there an option which I can use to get the p-values for all the positions?

**Comment by mparker2** [comment]
Hi @bhargava-morampalli, yes you can use the option `--fdr-threshold` to relax the filtering. However, positions are pre-filtered using a KS test to reduce the number of positions which have to be tested with the GMM method. The KS test uses the same `--fdr-threshold` parameter as well as the `--min-ks` parameter to filter out sites that are not worth testing. So you would need to relax both e.g. by setting `--fdr-threshold` to 1 and `--min-ks` to 0, to get results for all positions in the transcriptome. BUT this would increase the number of GMM models that need to be fit greatly and so will potentially increase the run time by quite a lot. I also have no idea how it will affect the false discovery rate for the GMM test.
